### ISSUE TITLE
Small problem with error handling for CLI edge cases

### ISSUE THREAD

**Issue by Ravlen** [vale-cli/vale#292]
Just something we noticed recently, and I finally figured out how to reproduce it.

If you pass a non-existent file to Vale by accident, it doesn't fail, but at least it doesn't crash:

```shell
$ vale --config ../.vale.ini --minAlertLevel error nofile.md
✔ 0 errors, 0 warnings and 0 suggestions in stdin.
```

If you combine it with a file that DOES exist, it fails silently again:

```shell
$ vale --config ../.vale.ini --minAlertLevel error README.md          
 README.md
 28:3  error  Link "[**User                       gitlab.InternalLinkExtension 
              documentation**](user/index.html)"                               
              must use the .md file extension.                                 
✖ 1 error, 0 warnings and 0 suggestions in 1 file.

$ vale --config ../.vale.ini --minAlertLevel error nofile.md README.md
✔ 0 errors, 0 warnings and 0 suggestions in stdin.
```

Finally, if you combine it with a file that does exist, but put the file names in the opposite order (existing file first, non-existing file second), it will completely crash:

```shell
$ vale --config ../.vale.ini --minAlertLevel error README.md nofile.md
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x173e9ad]
goroutine 632 [running]:
github.com/errata-ai/vale/v2/lint.(*Linter).lintFiles.func1.1(0x7ffeefbff8b3, 0x9, 0x0, 0x0, 0x1ad61a0, 0xc000f60a50, 0xc0001cd680, 0x18a7000)
        github.com/errata-ai/vale/v2/lint/lint.go:124 +0x4d
path/filepath.Walk(0x7ffeefbff8b3, 0x9, 0xc0010ad778, 0x0, 0x0)
        path/filepath/path.go:404 +0x6b
github.com/errata-ai/vale/v2/lint.(*Linter).lintFiles.func1(0x7ffeefbff8b3, 0x9, 0xc0005b1940, 0xc0001cd620, 0xc000200480, 0xc00036c660)
        github.com/errata-ai/vale/v2/lint/lint.go:123 +0x114
created by github.com/errata-ai/vale/v2/lint.(*Linter).lintFiles
        github.com/errata-ai/vale/v2/lint/lint.go:120 +0xb6
```

**Comment by Ravlen** [comment]
@jdkato One other problem that might be related, is that it'll crash the same way if you get your operators out of order:

```shell
$ vale --config ../.vale.ini README.md --minAlertLevel error   
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x173e9ad]

goroutine 2701 [running]:
github.com/errata-ai/vale/v2/lint.(*Linter).lintFiles.func1.1(0x7ffeefbff8ad, 0xf, 0x0, 0x0, 0x1ad61a0, 0xc002852240, 0x1016e7b, 0xc0022fdd20)
        github.com/errata-ai/vale/v2/lint/lint.go:124 +0x4d
path/filepath.Walk(0x7ffeefbff8ad, 0xf, 0xc001b1e778, 0x213aaa0, 0x213aaa0)
        path/filepath/path.go:404 +0x6b
github.com/errata-ai/vale/v2/lint.(*Linter).lintFiles.func1(0x7ffeefbff8ad, 0xf, 0xc000cac2c0, 0xc00157c660, 0xc0000b0480, 0xc0022e60c0)
        github.com/errata-ai/vale/v2/lint/lint.go:123 +0x114
created by github.com/errata-ai/vale/v2/lint.(*Linter).lintFiles
        github.com/errata-ai/vale/v2/lint/lint.go:120 +0xb6
```

**Comment by Ravlen** [comment]
The main thing is just to let Vale fail more gracefully in these cases.

**Comment by jdkato** [comment]
The first case (`vale nofile.md`) is expected, as it could be input of the form `vale "some text"` (note that it says "in stdin" rather than "n files").

The other cases will be fixed in the next release.
