### ISSUE TITLE
Android works... and doesn't

### ISSUE THREAD

**Issue by andreysamode** [vale-cli/vale#318]
Greetings,

I was able to successfully compile Vale for Android with this command:
`GOOS=android GOARCH=arm GOARM=7 CGO_ENABLED=1 CC=~/Desktop/android-ndk-r21d/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi23-clang go build -o valeAndroid ./cmd/vale`

When I run "./valeAndroid -h" on Android, I get the expected output:
```
vale - A command-line linter for prose.

Usage:	vale [options] [input...]
	vale myfile.md myfile1.md mydir1
	vale --output=JSON [input...]

Vale is a syntax-aware linter for prose...
```

But when I try to actually run it on either a text file or stdin, I get the following error:
```
$ echo "Test sdf" | ./valeAndroid
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0xb60b5480]

goroutine 101 [running]:
github.com/jdkato/regexp/internal/dfa.(*DFA).analyzeSearchHelper(0x85d760f0, 0x86bc3a4c, 0x85d7c0f0, 0x15, 0x85815900)
	/Users/mrandrey/Desktop/vale-2.8.1/vendor/github.com/jdkato/regexp/internal/dfa/dfa.go:157 +0x44
github.com/jdkato/regexp/internal/dfa.(*DFA).analyzeSearch(0x85d760f0, 0x86bc3a4c, 0x4ae)
	/Users/mrandrey/Desktop/vale-2.8.1/vendor/github.com/jdkato/regexp/internal/dfa/dfa.go:141 +0xf0
github.com/jdkato/regexp/internal/dfa.search(0x85d760f0, 0x85d761e0, 0x853a72f0, 0x867c6c3c, 0x0, 0x8684ac01, 0x0, 0x259, 0xb626b4f0, 0x861a28c0)
	/Users/mrandrey/Desktop/vale-2.8.1/vendor/github.com/jdkato/regexp/internal/dfa/search.go:107 +0x80
github.com/jdkato/regexp/internal/dfa.(*Searcher).Search(0x8618bdc8, 0xb6971eb0, 0x867c6c3c, 0x0, 0x0, 0x867c6c24, 0x0, 0x0, 0x0, 0x0)
	/Users/mrandrey/Desktop/vale-2.8.1/vendor/github.com/jdkato/regexp/internal/dfa/search.go:71 +0x100
github.com/jdkato/regexp.(*Regexp).doExecute(0x8618bd80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x867d03b0, 0x9, 0x0, 0x0, ...)
	/Users/mrandrey/Desktop/vale-2.8.1/vendor/github.com/jdkato/regexp/exec.go:442 +0x240
github.com/jdkato/regexp.(*Regexp).MatchString(...)
	/Users/mrandrey/Desktop/vale-2.8.1/vendor/github.com/jdkato/regexp/regexp.go:292
github.com/errata-ai/vale/v2/internal/check.Substitution.Run(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x86179c90, 0xc, 0x86179cd0, ...)
	/Users/mrandrey/Desktop/vale-2.8.1/internal/check/substitution.go:89 +0x58
github.com/errata-ai/vale/v2/internal/lint.(*Linter).lintBlock.func1(0x867da500, 0x867d03c0, 0x867d03b0, 0x9, 0x861a8980, 0x11, 0x867c6900, 0xb6970b70, 0x8618be00)
	/Users/mrandrey/Desktop/vale-2.8.1/internal/lint/lint.go:236 +0x60
created by github.com/errata-ai/vale/v2/internal/lint.(*Linter).lintBlock
	/Users/mrandrey/Desktop/vale-2.8.1/internal/lint/lint.go:234 +0x19c
```

Do you have any ideas on what this might be about or how to fix it?

Thanks,
Andrey

**Comment by jdkato** [comment]
No, as I said in #314, I think this is something you'll have to work through on your own. I currently don't have time to investigate issues for a platform that I don't support.
