### ISSUE TITLE
Vale exits with panic: runtime error: slice bounds out of range [:53] with capacity 52

### ISSUE THREAD

**Issue by gary-vertica** [vale-cli/vale#370]
On Linux, using 2.11.0 (downloaded binary), I'm testing Vale on our documentation source that's written in MadCap Flare (which is, basically, HTML plus some Flare-specific tags). It works fine on most files, but on a few it crashes:

```
panic: runtime error: slice bounds out of range [:53] with capacity 52

goroutine 13 [running]:
github.com/errata-ai/vale/v2/internal/check.re2Loc(...)
	/home/runner/work/vale/vale/internal/check/definition.go:132
github.com/errata-ai/vale/v2/internal/check.makeAlert({{{0x0, 0x0}, {0x0, 0x0, 0x0}}, {0x0, 0x0}, {0xc00160e0b0, 0xe}, {0xc00160e0f0, ...}, ...}, ...)
	/home/runner/work/vale/vale/internal/check/definition.go:136 +0x29b
github.com/errata-ai/vale/v2/internal/check.Capitalization.Run({{{{0x0, 0x0}, {0x0, 0x0, 0x0}}, {0x0, 0x0}, {0xc00160e0b0, 0xe}, {0xc00160e0f0, ...}, ...}, ...}, ...)
	/home/runner/work/vale/vale/internal/check/capitalization.go:95 +0x10c
github.com/errata-ai/vale/v2/internal/lint.(*Linter).lintBlock(0xc0005198c0, 0xc00080c160, {{0xc0015e6870, 0xef}, 0x5, {0xc00064bda0, 0x13}, {0xc0006eb200, 0x35}}, 0x9, ...)
	/home/runner/work/vale/vale/internal/lint/lint.go:225 +0x229
github.com/errata-ai/vale/v2/internal/lint.Linter.lintScope({0xc00050c400, 0x0, 0x0, 0xc000360630, 0x12a48e0, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	/home/runner/work/vale/vale/internal/lint/ast.go:133 +0x44b
github.com/errata-ai/vale/v2/internal/lint.Linter.lintHTMLTokens({0xc00050c400, 0x0, 0x0, 0xc000360630, 0x12a48e0, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	/home/runner/work/vale/vale/internal/lint/ast.go:105 +0xad0
github.com/errata-ai/vale/v2/internal/lint.(*Linter).lintHTML(0xc0006d3980, 0xc00080c160)
	/home/runner/work/vale/vale/internal/lint/html.go:27 +0xcb
github.com/errata-ai/vale/v2/internal/lint.(*Linter).lintFile(0xc0006d3980, {0x7ffc680962b3, 0xc0017103c0})
	/home/runner/work/vale/vale/internal/lint/lint.go:182 +0x405
github.com/errata-ai/vale/v2/internal/lint.(*Linter).lintFiles.func1.1.1({0x7ffc680962b3, 0x1})
	/home/runner/work/vale/vale/internal/lint/lint.go:119 +0x5b
created by github.com/errata-ai/vale/v2/internal/lint.(*Linter).lintFiles.func1.1
	/home/runner/work/vale/vale/internal/lint/lint.go:117 +0x21d
```

I'm using the Microsoft ruleset:

```	
        StylesPath = /home/myhome/git/styles
	MinAlertLevel = suggestion

	[*.htm]
	BasedOnStyles = Microsoft
```

After commenting out lines in one of the problematic source files to narrow down the issue, I was able to isolate the crash (at least in one case) to an HTML entity (`&#160;` aka non-breaking space) within a heading that will trigger the Microsoft.Headings  rule for sentence-style capitalization. Here's a minimal reproducer:

``` 
<?xml version="1.0" encoding="utf-8"?>
<html xmlns:MadCap="http://www.madcapsoftware.com/Schemas/MadCap.xsd">
    <head>
    </head>
    <body>
        <h1>Something&#160;Weird is happening With Vale With Entities</h1>
    </body>
</html>
```

The bug seems sensitive to the content of the heading (perhaps its length?), in addition to the entity in the line. Specifically, if I delete some text after the entity in the heading, the error does not trigger. I.e. delete the word "Entities" from the h1 tag, and vale doesn't crash. Also, it doesn't trigger the heading capitalization rule suggestion. Deleting the entity has vale flag the heading with the sentence-style capitalization rule.

**Comment by jdkato** [comment]
Thanks for the detailed report.

This will be fixed in the next release.
