### ISSUE TITLE
vale crashes with 32C/64T AMDEpyc 7504

### ISSUE THREAD

**Issue by 5u623l20** [vale-cli/vale#610]
- OS FreeBSD 13.2-RELEASE
- Install method : source
- Vale version : vale version master

Running Vale crashes:
```
❯ vale .
panic: runtime error: index out of range [0] with length 0

goroutine 1241 [running]:
github.com/errata-ai/vale/v2/internal/lint.getScope({0x141d100?, 0x852a4c540?, 0xc292f2?}, {0xbf631d?, 0x0?}, {0x852b0c06c?, 0x852b21600?})
	github.com/errata-ai/vale/v2/internal/lint/ast.go:291 +0x225
github.com/errata-ai/vale/v2/internal/lint.Linter.lintHTMLTokens({{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x852b21600, 0x853dbc000, 0x13e3980, 0x1, ...}, ...)
	github.com/errata-ai/vale/v2/internal/lint/ast.go:104 +0x12d3
github.com/errata-ai/vale/v2/internal/lint.(*Linter).lintADoc(0x853db8000, 0x85170e000)
	github.com/errata-ai/vale/v2/internal/lint/adoc.go:133 +0x36b
github.com/errata-ai/vale/v2/internal/lint.(*Linter).lintFile(0x853db8000, {0x852b0c040?, 0x8ad663701?})
	github.com/errata-ai/vale/v2/internal/lint/lint.go:168 +0x405
github.com/errata-ai/vale/v2/internal/lint.(*Linter).lintFiles.func1.1.1({0x852b0c040?, 0x0?})
	github.com/errata-ai/vale/v2/internal/lint/lint.go:114 +0x5b
created by github.com/errata-ai/vale/v2/internal/lint.(*Linter).lintFiles.func1.1
	github.com/errata-ai/vale/v2/internal/lint/lint.go:112 +0x20c
```

However running vale on single file or editor works fine.

**Comment by jdkato** [comment]
Should be fixed in the next release.
