### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by vigneshmanick** [vale-cli/vale#615]
### Check for existing issues

- [X] Completed

### Environment

- OS - Linux
- Install method - direct download
- vale version 2.25.1

### Describe the bug / provide steps to reproduce it

When running vale within a gitlab  step on a folder with asciidoc files the following error occurs.

```sh
./vale docs
panic: runtime error: index out of range [2004] with length 1691
goroutine 138 [running]:
github.com/errata-ai/vale/v2/internal/lint.(*Linter).resetContext(...)
	/home/runner/work/vale/vale/internal/lint/ast.go:242
github.com/errata-ai/vale/v2/internal/lint.(*Linter).lintHTMLTokens(0xc0050a9420, 0xc0012ca160, {0xc003b84000, 0xdd8, 0x1000}, 0xcfd2af?)
	/home/runner/work/vale/vale/internal/lint/ast.go:119 +0x1485
github.com/errata-ai/vale/v2/internal/lint.(*Linter).lintADoc(0xc0050a9420, 0xc0012ca160)
	/home/runner/work/vale/vale/internal/lint/adoc.go:133 +0x2dc
github.com/errata-ai/vale/v2/internal/lint.(*Linter).lintFile(0xc0050a9420, {0xc004d0ca20?, 0xc000083f01?})
	/home/runner/work/vale/vale/internal/lint/lint.go:180 +0x46d
github.com/errata-ai/vale/v2/internal/lint.(*Linter).lintFiles.func1.1.1({0xc004d0ca20?, 0x0?})
	/home/runner/work/vale/vale/internal/lint/lint.go:126 +0x5b
created by github.com/errata-ai/vale/v2/internal/lint.(*Linter).lintFiles.func1.1
	/home/runner/work/vale/vale/internal/lint/lint.go:124 +0x20c
```

Thanks!

**Comment by jdkato** [comment]
Should be fixed in v2.25.2.
