### ISSUE TITLE
pre-commit environment fails to initialise with error: error obtaining VCS status: exit status 128

### ISSUE THREAD

**Issue by alunduil** [vale-cli/vale#926]
### Check for existing issues

- [X] Completed

### Environment

# os-release

```
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

# Install Method

git commit -av using pre-commit installed as a hook with the following configuration stanza:

```
  - repo: https://github.com/errata-ai/vale
    rev: v3.9.1
    hooks:
      - id: vale
        exclude: '^(styles/|LICENSE$|\.envrc$)'
        exclude_types:
          - gitignore
          - ini
          - json
          - nix
          - python
          - toml
          - yaml
```

# Vale Version

3.9.1

# Full error output from pre-commit

### version information

```
pre-commit version: 3.3.3
git --version: git version 2.45.2
sys.version:
    3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
sys.executable: /workspaces/zfs-replicate/.venv/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/home/vscode/.cache/pre-commit/repoyo8mfk4g/golangenv-default/.go/bin/go', 'install', './...')
return code: 1
stdout: (none)
stderr:
    go: downloading github.com/adrg/strutil v0.3.0
    go: downloading github.com/Masterminds/sprig/v3 v3.2.3
    go: downloading github.com/adrg/xdg v0.4.0
    go: downloading github.com/jdkato/twine v0.10.1
    go: downloading github.com/bmatcuk/doublestar/v4 v4.6.0
    go: downloading github.com/mholt/archiver/v3 v3.5.1
    go: downloading github.com/gobwas/glob v0.2.3
    go: downloading github.com/olekukonko/tablewriter v0.0.4
    go: downloading github.com/otiai10/copy v1.7.0
    go: downloading github.com/pterm/pterm v0.12.76
    go: downloading github.com/spf13/pflag v1.0.5
    go: downloading golang.org/x/exp v0.0.0-20231006140011-7918f672742d
    go: downloading github.com/jdkato/go-tree-sitter-julia v0.1.0
    go: downloading github.com/smacker/go-tree-sitter v0.0.0-20240514083259-c5d1f3f5f99e
    go: downloading github.com/errata-ai/ini v1.63.0
    go: downloading github.com/karrick/godirwalk v1.16.1
    go: downloading github.com/antonmedv/expr v1.12.0
    go: downloading github.com/d5/tengo/v2 v2.10.0
    go: downloading github.com/errata-ai/regexp2 v1.7.0
    go: downloading gopkg.in/yaml.v2 v2.4.0
    go: downloading github.com/mitchellh/mapstructure v1.4.0
    go: downloading github.com/niklasfasching/go-org v1.6.6
    go: downloading github.com/remeh/sizedwaitgroup v1.0.0
    go: downloading github.com/yuin/goldmark v1.5.6
    go: downloading golang.org/x/net v0.23.0
    go: downloading github.com/Masterminds/goutils v1.1.1
    go: downloading github.com/Masterminds/semver/v3 v3.2.0
    go: downloading github.com/google/uuid v1.1.1
    go: downloading github.com/huandu/xstrings v1.3.3
    go: downloading github.com/imdario/mergo v0.3.11
    go: downloading github.com/mitchellh/copystructure v1.0.0
    go: downloading github.com/shopspring/decimal v1.2.0
    go: downloading github.com/spf13/cast v1.3.1
    go: downloading golang.org/x/crypto v0.21.0
    go: downloading github.com/andybalholm/brotli v1.0.1
    go: downloading github.com/dsnet/compress v0.0.2-0.20210315054119-f66993602bf5
    go: downloading github.com/klauspost/compress v1.11.4
    go: downloading github.com/golang/snappy v0.0.4
    go: downloading github.com/klauspost/pgzip v1.2.5
    go: downloading github.com/pierrec/lz4/v4 v4.1.2
    go: downloading github.com/ulikunitz/xz v0.5.10
    go: downloading github.com/nwaples/rardecode v1.1.0
    go: downloading github.com/xi2/xz v0.0.0-20171230120015-48954b6210f8
    go: downloading github.com/mattn/go-runewidth v0.0.15
    go: downloading atomicgo.dev/cursor v0.2.0
    go: downloading atomicgo.dev/keyboard v0.2.9
    go: downloading atomicgo.dev/schedule v0.1.0
    go: downloading github.com/gookit/color v1.5.4
    go: downloading github.com/lithammer/fuzzysearch v1.1.8
    go: downloading golang.org/x/term v0.18.0
    go: downloading golang.org/x/text v0.14.0
    go: downloading github.com/montanaflynn/stats v0.7.1
    go: downloading gopkg.in/neurosnap/sentences.v1 v1.0.7
    go: downloading github.com/mitchellh/reflectwalk v1.0.0
    go: downloading github.com/rivo/uniseg v0.4.4
    go: downloading github.com/containerd/console v1.0.3
    go: downloading github.com/xo/terminfo v0.0.0-20220910002029-abceb7e1c41e
    go: downloading golang.org/x/sys v0.18.0
    error obtaining VCS status: exit status 128
    	Use -buildvcs=false to disable VCS stamping.
```

```
Traceback (most recent call last):
  File "/workspaces/zfs-replicate/.venv/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/workspaces/zfs-replicate/.venv/lib/python3.10/site-packages/pre_commit/main.py", line 386, in main
    return hook_impl(
  File "/workspaces/zfs-replicate/.venv/lib/python3.10/site-packages/pre_commit/commands/hook_impl.py", line 271, in hook_impl
    return retv | run(config, store, ns)
  File "/workspaces/zfs-replicate/.venv/lib/python3.10/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/workspaces/zfs-replicate/.venv/lib/python3.10/site-packages/pre_commit/repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "/workspaces/zfs-replicate/.venv/lib/python3.10/site-packages/pre_commit/repository.py", line 95, in _hook_install
    lang.install_environment(
  File "/workspaces/zfs-replicate/.venv/lib/python3.10/site-packages/pre_commit/languages/golang.py", line 152, in install_environment
    lang_base.setup_cmd(prefix, ('go', 'install', './...'), env=env)
  File "/workspaces/zfs-replicate/.venv/lib/python3.10/site-packages/pre_commit/lang_base.py", line 86, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/workspaces/zfs-replicate/.venv/lib/python3.10/site-packages/pre_commit/util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/home/vscode/.cache/pre-commit/repoyo8mfk4g/golangenv-default/.go/bin/go', 'install', './...')
return code: 1
stdout: (none)
stderr:
    go: downloading github.com/adrg/strutil v0.3.0
    go: downloading github.com/Masterminds/sprig/v3 v3.2.3
    go: downloading github.com/adrg/xdg v0.4.0
    go: downloading github.com/jdkato/twine v0.10.1
    go: downloading github.com/bmatcuk/doublestar/v4 v4.6.0
    go: downloading github.com/mholt/archiver/v3 v3.5.1
    go: downloading github.com/gobwas/glob v0.2.3
    go: downloading github.com/olekukonko/tablewriter v0.0.4
    go: downloading github.com/otiai10/copy v1.7.0
    go: downloading github.com/pterm/pterm v0.12.76
    go: downloading github.com/spf13/pflag v1.0.5
    go: downloading golang.org/x/exp v0.0.0-20231006140011-7918f672742d
    go: downloading github.com/jdkato/go-tree-sitter-julia v0.1.0
    go: downloading github.com/smacker/go-tree-sitter v0.0.0-20240514083259-c5d1f3f5f99e
    go: downloading github.com/errata-ai/ini v1.63.0
    go: downloading github.com/karrick/godirwalk v1.16.1
    go: downloading github.com/antonmedv/expr v1.12.0
    go: downloading github.com/d5/tengo/v2 v2.10.0
    go: downloading github.com/errata-ai/regexp2 v1.7.0
    go: downloading gopkg.in/yaml.v2 v2.4.0
    go: downloading github.com/mitchellh/mapstructure v1.4.0
    go: downloading github.com/niklasfasching/go-org v1.6.6
    go: downloading github.com/remeh/sizedwaitgroup v1.0.0
    go: downloading github.com/yuin/goldmark v1.5.6
    go: downloading golang.org/x/net v0.23.0
    go: downloading github.com/Masterminds/goutils v1.1.1
    go: downloading github.com/Masterminds/semver/v3 v3.2.0
    go: downloading github.com/google/uuid v1.1.1
    go: downloading github.com/huandu/xstrings v1.3.3
    go: downloading github.com/imdario/mergo v0.3.11
    go: downloading github.com/mitchellh/copystructure v1.0.0
    go: downloading github.com/shopspring/decimal v1.2.0
    go: downloading github.com/spf13/cast v1.3.1
    go: downloading golang.org/x/crypto v0.21.0
    go: downloading github.com/andybalholm/brotli v1.0.1
    go: downloading github.com/dsnet/compress v0.0.2-0.20210315054119-f66993602bf5
    go: downloading github.com/klauspost/compress v1.11.4
    go: downloading github.com/golang/snappy v0.0.4
    go: downloading github.com/klauspost/pgzip v1.2.5
    go: downloading github.com/pierrec/lz4/v4 v4.1.2
    go: downloading github.com/ulikunitz/xz v0.5.10
    go: downloading github.com/nwaples/rardecode v1.1.0
    go: downloading github.com/xi2/xz v0.0.0-20171230120015-48954b6210f8
    go: downloading github.com/mattn/go-runewidth v0.0.15
    go: downloading atomicgo.dev/cursor v0.2.0
    go: downloading atomicgo.dev/keyboard v0.2.9
    go: downloading atomicgo.dev/schedule v0.1.0
    go: downloading github.com/gookit/color v1.5.4
    go: downloading github.com/lithammer/fuzzysearch v1.1.8
    go: downloading golang.org/x/term v0.18.0
    go: downloading golang.org/x/text v0.14.0
    go: downloading github.com/montanaflynn/stats v0.7.1
    go: downloading gopkg.in/neurosnap/sentences.v1 v1.0.7
    go: downloading github.com/mitchellh/reflectwalk v1.0.0
    go: downloading github.com/rivo/uniseg v0.4.4
    go: downloading github.com/containerd/console v1.0.3
    go: downloading github.com/xo/terminfo v0.0.0-20220910002029-abceb7e1c41e
    go: downloading golang.org/x/sys v0.18.0
    error obtaining VCS status: exit status 128
    	Use -buildvcs=false to disable VCS stamping.
``````

### Describe the bug / provide steps to reproduce it

1. Configure pre-commit with the above stanza.
3. Create a text file such as README.md
4. Run `pre-commit run --all-files`

**Comment by ViggoC** [comment]
add `GOFLAGS=-buildvcs=false` before `pre-commit` works for me. e.g.
```bash
GOFLAGS=-buildvcs=false pre-commit run --all-files
```

**Comment by alunduil** [comment]
Marking this closed since there is a workaround and I suspect this is an interaction between environment and pre-commit more than something vale can do anything about. Re-open if I've got this wrong or if actual documentation would be preferred.
